web_disk: 
	g++ -fopenmp -O3 -Wall ../suffixcore/tialloc/tialloc.cpp ../suffixcore/SuffixNode.cpp ../URIStore.cpp -I../suffixcore -I../suffixtrans -I../suffixcore/tialloc ../suffixcore_optional/SuffixNodeStoreDisk.cpp -o web_disk -I.. -I../suffixcore_optional -I../suffixcore -I. web_disk.cpp -L../zlib-1.2.8 -I../zlib-1.2.8 -lz -static
